id: I4CB758BB
ocr_import_info:
  source: bdrc
  software: google_books
  batch: batch_2022
  expected_default_language: bo
  bdrc_scan_id: W3CN1804
  ocr_info:
    timestamp: 03/21/23T14:16:45
    html: html.zip
    txt: txt.zip
    images: images.zip
  op_import_options: {}
  op_import_version: 0.11.9
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2024-02-28 23:07:26.452504+00:00
last_modified: 2024-02-28 23:07:26.452515+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN1804
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN1804
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བེམ་ཤེས་ལྡན་མིན་འདུ་བྱེད་གསུམ་གྱི་གྲོས་འདེབས་ལས་བྱུང་བ་སྨྱོན་པའི་ཟློས་གར་གསལ་བར་བྱེད་པའི་མེ་ལོང་།
  languages:
  - bo
  author: ཀྱེ་རྡོར་མཁན་པོ་ངག་དབང་མཁས་གྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.9657088239792017
  ocr_word_median_confidence_index: 1.0
bases:
  I3CN1806:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN1806
      total_pages: 24
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN1806.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9657088239792017
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
